name: CI/CD Good Practices

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        echo "Building the project..."
        
        echo "Project build step completed."

    - name: Run tests
      run: |
        echo "Running tests..."
        
        echo "Tests passed!"
      
    - name: Deploy
      env:
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      run: |
        echo "Deploying to production..."
        echo "Deploying with password: $DEPLOY_PASSWORD"

    - name: Manual Approval Step
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Waiting for manual approval..."
