name: CI/CD Good Practices

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        # Используем актуальные пакеты
        npm install

    - name: Build project
      run: |
        echo "Building the project..."
        # Обрабатываем ошибки и завершаем выполнение, если что-то пойдет не так
        npm run build

    - name: Run tests
      run: |
        echo "Running tests..."
        # Добавлена проверка статуса тестов
        npm test

    - name: Deploy
      # Используем переменные окружения для защиты чувствительных данных
      env:
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      run: |
        echo "Deploying to production..."
        # Используем секреты вместо явного пароля
        echo "Deploying with password: $DEPLOY_PASSWORD"

    - name: Manual Approval Step
      # Реальный шаг для ручной проверки перед деплоем
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Waiting for manual approval..."

